### ISSUE TITLE
REST-api not working

### ISSUE THREAD

**Issue by artturimatias** [osma/annif#10]
Service gives response code 200 but no content
Tested also here:
http://api.annif.org/doc/#!/Automatic32subject32indexing/post_autoindex

**Comment by osma** [comment]
Server has run out of disk space. Fixing...

We've started a new implementation at https://github.com/NatLibFi/Annif . It will take a while to reach the level of functionality in this prototype though. Eventually the new implementation will supersede this one. You may want to follow development.

**Comment by osma** [comment]
Should be working now.

**Comment by artturimatias** [comment]
Works, thanks! 
BTW: We have Annif now in our Master's thesis online publishing form so that users can choose keywords by themselves (planned to run in production in December). Do you think that this rest api is more or less permanent during development?

**Comment by osma** [comment]
We will notify you before any major changes. But eventually this REST API will probably go away (since it's really a prototype, not something we expect to maintain in the long term), replaced by the new implementation that has a similar REST API but with more functionality. It has an `analyze` method which does the same as this API. 

You may have to adjust the API endpoint URL and some parameters in your application code. I expect that both APIs will be available in parallel for a while.

**Comment by artturimatias** [comment]
Ok, good to know.
